STACK SEGMENT PARA STACK
  DB 64 DUP (' ')
STACK ENDS

DATA SEGMENT PARA 'DATA'

BALL_X DW 0A0H
BALL_Y DW 64H
BALL_SIZE DW 04H
TIME_PREV DB 0H ; TO CHECK PREVIOUS VALUE OF TIME (make sure it has changed)
VELOCITY_X DW 05H
VELOCITY_Y DW 02H
WINDOW_WIDTH DW 140H ;320 PIXELS
WINDOW_HEIGHT DW 0C8H ;200 PIXELS
WINDOW_BOUNDARIES DW 6  ; without this boundaries the pixel will appear in random place during collosion then 
                        ; disappear instantly,this is beacuse we are not checking where was the last position our ball was
                        ; so we have to make some boundaries to prevent this from happening
BALL_ORG_X DW 0A0H
BALL_ORG_Y DW 64H

PADDLE_LEFT_X DW 06H
PADDLE_LEFT_Y DW 02H

PADDLE_RIGHT_X DW 135H
PADDLE_RIGHT_Y DW 02H

PADDLE_WIDTH DW 05H
PADDLE_HEIGHT DW 1FH
PADDLE_VELOCITY DW 05H

PADDLE_LEFT_PLAYER_PONTS DB 0
PADDLE_RIGHT_PLAYER_PONTS DB 0

TEXT_LEFT_PLAYER_POINTS DB '0','$'
TEXT_RIGHT_PLAYER_POINTS DB '0','$'

GAME_ACTIVE DB 1 ; 1:TRUE 0:FALSE
TEXT_GAME_OVER DB 'GAME OVER','$'
TEXT_GAME_OVER_WINNER DB 'PLAYER 1 ATE IT ;)','$'
WINNER_INDEX DB 0

TEXT_GAME_OVER_PLAY_AGAIN DB 'PRESS ESC TO PLAY AGAIN','$'
TEXT_GAME_OVER_MAIN_MENU DB  '  PRESS E TO MAIN MENU  ','$'
TEXT_MAIN_MENU DB '--MAIN MENU--','$'
TEXT_MAIN_MENU_SINGLE_PLAYER DB 'SINGLE PLAYER-S','$'
TEXT_MAIN_MENU_MULTI_PLAYER DB 'MULTI PLAYER-M','$'

CURRENT_SCENE DB 0 ;0:MAIN MENU 1:GAME

AI_LEFT_PADDLE_CONTROLLED DB 0





DATA ENDS

CODE SEGMENT PARA 'CODE'

  MAIN PROC FAR
  ASSUME CS:CODE, DS:DATA ,SS:STACK
  PUSH DS
  XOR AX,AX
  PUSH AX
  MOV AX,DATA ; initialize data segment
  MOV DS,AX

  MOV AH,00h ; graphics mode
  MOV AL,13h
  INT 10h

  MOV AH,0Bh ;background colour
  MOV BH,00h
  MOV BL,00h 
  INT 10h

CHECK_TIME:

 CMP CURRENT_SCENE,00h
 JE SHOW_MAIN_MENU

 CMP GAME_ACTIVE,00h
 JE SHOW_GAME_OVER

 MOV AH,2CH ; FOR TIME CH=HOURS CL=MINUTES DH=SECONDS 
 INT 21H 
 CMP DL,TIME_PREV ; WE ARE COMPARING 8 BITS THAT'S WHY TIME_PRIV IS DB
 JE CHECK_TIME
 MOV TIME_PREV,DL ; UPDATE TIME
 




 MOV AL,00H    ; removing pixel by changing its colour to black
 CALL DRAW_PADDLES
 CALL MOV_PADDLES
 MOV AL,0FH
 CALL DRAW_PADDLES

 MOV AL,00H    ; removing pixel by changing its colour to black
 CALL DRAW_BALL
 CALL MOV_BALL
 MOV AL,0FH    ; COLOUR IS WHITE
 CALL DRAW_BALL 

 CALL USER_INTERFACE

 

JMP CHECK_TIME

SHOW_GAME_OVER:
 CALL DRAW_GAME_OVER_UI
 JMP CHECK_TIME
 

SHOW_MAIN_MENU:
 CALL DRAW_MAIN_MENU 
 JMP CHECK_TIME






 MOV AH,00h ; add wait
 INT 16H 



  MOV AX,4C00H ; TERMINATE
  INT 21H
  MAIN ENDP


;-----------------------------------------
 DRAW_BALL  PROC NEAR
  
  MOV CX,BALL_X ; X starting position
  MOV DX,BALL_Y ; Y starting position

  LOOP_DRAW_BALL_HORIZONTAL:
  MOV AH,0CH ;WRITE GRAPHICS PIXEL
  MOV BH,0H  ; PAGE NUMBER
  INT 10H
  INC CX
  MOV BX,CX
  SUB BX,BALL_X
  CMP BX,BALL_SIZE
  JNG LOOP_DRAW_BALL_HORIZONTAL
  
  MOV CX,BALL_X ; moving to  next line by moving to initial position
  INC DX ; move one step down
  MOV BX,DX
  SUB BX,BALL_Y
  CMP BX,BALL_SIZE
  JNG LOOP_DRAW_BALL_HORIZONTAL

  RET
 DRAW_BALL ENDP 
;-----------------------------------------
 RESET_POS PROC NEAR
   MOV AX ,BALL_ORG_X
   MOV BALL_X,AX

   MOV AX ,BALL_ORG_Y
   MOV BALL_Y,AX
  
  RET
  RESET_POS ENDP
;----------------------------------------
  MOV_BALL PROC NEAR

  MOV AX,VELOCITY_X
  MOV BX,VELOCITY_Y
  ADD BALL_X,AX   ; MOVE BALL X AXIS
  
  MOV AX ,WINDOW_BOUNDARIES
  CMP BALL_X,AX
  ; JL RESET_POS_CALL
  JL GIVE_POINTS_LEFT_PLAYER

  MOV AX,WINDOW_WIDTH
  SUB AX,WINDOW_BOUNDARIES
  CMP BALL_X,AX
  ; JG  RESET_POS_CALL
  JG GIVE_POINTS_RIGHT_PLAYER
  JMP MOV_BALL_IN_Y_AXIS


  GIVE_POINTS_LEFT_PLAYER:
   INC PADDLE_RIGHT_PLAYER_PONTS
  ;  CALL RESET_POS
   CALL UPDATE_TEXT_POINTS_RIGHT_PLAYER

    NEG VELOCITY_X      ; Bounce back
    MOV AX,WINDOW_BOUNDARIES
    MOV BALL_X,AX 

   CMP PADDLE_RIGHT_PLAYER_PONTS,5H
   JG GAME_OVER
   RET


   GIVE_POINTS_RIGHT_PLAYER:
    INC PADDLE_LEFT_PLAYER_PONTS
    ; CALL RESET_POS
    CALL UPDATE_TEXT_POINTS_LEFT_PLAYER

    NEG VELOCITY_X      ; Bounce back
    MOV AX,WINDOW_WIDTH
    SUB AX,WINDOW_BOUNDARIES
    SUB AX,BALL_SIZE
    MOV BALL_X,AX

    CMP PADDLE_LEFT_PLAYER_PONTS,5H
    JG GAME_OVER
    RET


   GAME_OVER:   ; AFTER REACHING 5 PONTS RESET GAME
    CMP PADDLE_LEFT_PLAYER_PONTS,5H ; FIRST CHECK THE WINNER 
    JNL WINNER_IS_LEFT_PLAYER
    JMP WINNER_IS_RIGHT_PLAYER
     
     WINNER_IS_LEFT_PLAYER:
      MOV WINNER_INDEX,01H ;  MEANS PLAYER 1
      JMP CONTINUE

     WINNER_IS_RIGHT_PLAYER:
      MOV WINNER_INDEX,02H  ; INDEX 1 MEANS PLAYER 2
      
   CONTINUE:
    MOV PADDLE_LEFT_PLAYER_PONTS,00H
    MOV PADDLE_RIGHT_PLAYER_PONTS,00H
    CALL UPDATE_TEXT_POINTS_LEFT_PLAYER
    CALL UPDATE_TEXT_POINTS_RIGHT_PLAYER 
    MOV GAME_ACTIVE,00H
    RET

  RESET_POS_CALL:
     CALL RESET_POS
     RET

 MOV_BALL_IN_Y_AXIS:
  ADD BALL_Y,BX   ; MOVE BALL Y AXIS

  MOV AX,WINDOW_BOUNDARIES 
  CMP BALL_Y,AX
  JL NEG_VELOCITY_Y

  MOV AX,WINDOW_HEIGHT
  SUB AX,WINDOW_BOUNDARIES  
  CMP BALL_Y,AX            ; boundaries checked with ball y axis position and window height
  JG NEG_VELOCITY_Y

;-------COLLOSION-------
;CHECK IF BALL COLLIDES WITH RIGHT PADDLE
; AABB COLLOSION
; BALL_X+BALL_SIZE > PADDLE_RIGHT_X   &&  BALL_X < PADDLE_RIGHT_X + PADDLE_WIDTH
; BALL_Y+BALL_SIZE> PADDLE_RIGHT_Y    &&  BALL_Y < PADDLE_RIGHT_Y + PADDLE_HEIGHT


MOV AX,BALL_X
ADD AX,BALL_SIZE
CMP AX,PADDLE_RIGHT_X
JNG CHECK_LEFT_COLLOSION ;NO COLLOSION,CHECK LEFT PADDLE

MOV AX,PADDLE_RIGHT_X
ADD AX,PADDLE_WIDTH
CMP BALL_X,AX
JNL CHECK_LEFT_COLLOSION

MOV AX,BALL_Y
ADD AX,BALL_SIZE
CMP AX,PADDLE_RIGHT_Y
JNG CHECK_LEFT_COLLOSION

MOV AX,PADDLE_RIGHT_Y
ADD AX,PADDLE_HEIGHT
CMP BALL_Y,AX
JNL CHECK_LEFT_COLLOSION


; THERE IS COLLOSION DETECTED WITH RIGHT PADDLE
NEG VELOCITY_X
RET ; EXIT AS BALL WON'T COLLIDE WITH 2 PADELS AT SAME TIME






;CHECK IF BALL COLLIDES WITH LEFT PADDLE
; BALL_X+BALL_SIZE > PADDLE_LEFT_X   &&  BALL_X < PADDLE_LEFT_X + PADDLE_WIDTH
; BALL_Y+BALL_SIZE> PADDLE_LEFT_Y    &&  BALL_Y < PADDLE_LEFT_Y + PADDLE_HEIGHT
CHECK_LEFT_COLLOSION:

MOV AX,BALL_X
ADD AX,BALL_SIZE
CMP AX,PADDLE_LEFT_X
JNG EXIT_COLLOSION ;NO COLLOSION

MOV AX,PADDLE_LEFT_X
ADD AX,PADDLE_WIDTH
CMP BALL_X,AX
JNL EXIT_COLLOSION

MOV AX,BALL_Y
ADD AX,BALL_SIZE
CMP AX,PADDLE_LEFT_Y
JNG EXIT_COLLOSION

MOV AX,PADDLE_LEFT_Y
ADD AX,PADDLE_HEIGHT
CMP BALL_Y,AX
JNL EXIT_COLLOSION

NEG VELOCITY_X
RET ;


NEG_VELOCITY_Y:
    NEG VELOCITY_Y
    RET


EXIT_COLLOSION:
   RET

  MOV_BALL ENDP
;--------------------------------------- 
DRAW_PADDLES PROC NEAR

; DRAWING LEFT PADDLE
  MOV CX,PADDLE_LEFT_X; X starting position
  MOV DX,PADDLE_LEFT_Y; Y starting position

  LOOP_DRAW_PADDLE_LEFT_HORIZONTAL:
    MOV AH,0CH ;WRITE GRAPHICS PIXEL
    MOV BH,0H  ; PAGE NUMBER
    INT 10H
    INC CX
    MOV BX,CX
    SUB BX,PADDLE_LEFT_X
    CMP BX,PADDLE_WIDTH
    JNG LOOP_DRAW_PADDLE_LEFT_HORIZONTAL

  MOV CX,PADDLE_LEFT_X; moving to  next line by moving to initial position
  INC DX ; move one step down
  MOV BX,DX
  SUB BX,PADDLE_LEFT_Y
  CMP BX,PADDLE_HEIGHT
  JNG LOOP_DRAW_PADDLE_LEFT_HORIZONTAL



; DRAWING RIGHT PADDLE
 MOV CX,PADDLE_RIGHT_X; X starting position
  MOV DX,PADDLE_RIGHT_Y; Y starting position

  LOOP_DRAW_PADDLE_RIGHT_HORIZONTAL:
    MOV AH,0CH ;WRITE GRAPHICS PIXEL
    MOV BH,0H  ; PAGE NUMBER
    INT 10H
    INC CX
    MOV BX,CX
    SUB BX,PADDLE_RIGHT_X
    CMP BX,PADDLE_WIDTH
    JNG LOOP_DRAW_PADDLE_RIGHT_HORIZONTAL

  MOV CX,PADDLE_RIGHT_X; moving to  next line by moving to initial position
  INC DX ; move one step down
  MOV BX,DX
  SUB BX,PADDLE_RIGHT_Y
  CMP BX,PADDLE_HEIGHT
  JNG LOOP_DRAW_PADDLE_RIGHT_HORIZONTAL





RET
DRAW_PADDLES ENDP
;--------------------------------------
MOV_PADDLES PROC NEAR
; CHECK IF ANY KEY IS BEING PRESSED
 MOV AH,01H   
 INT 16H
 JZ CHECK_RIGHT_PADDLE  ; IF ZF=1 

; CHECK WHICH KEY IS PRESSED
 MOV AH,00h   
 INT 16H





; FOR MULTI PLAYER MODE

 ; W,w FOR LEFT PADDLE UP
 CMP AL,77H ;w
 JE LEFT_PADDLE_UP
 CMP AL,57H ;W
 JE LEFT_PADDLE_UP

 ;S,s FOR left PADDLE down
 CMP AL,73H ;w
 JE LEFT_PADDLE_DOWN
 CMP AL,53H ;W
 JE LEFT_PADDLE_DOWN
 JMP CHECK_RIGHT_PADDLE


  


 LEFT_PADDLE_UP:
   MOV AX,PADDLE_VELOCITY
   SUB PADDLE_LEFT_Y,AX
   
   MOV AX,WINDOW_BOUNDARIES
   CMP PADDLE_LEFT_Y,AX
   JL FIX_PADDLE_LEFT_TOP


   JMP CHECK_RIGHT_PADDLE

   FIX_PADDLE_LEFT_TOP:
     MOV AX,WINDOW_BOUNDARIES
     MOV PADDLE_LEFT_Y,AX
     JMP CHECK_RIGHT_PADDLE


 LEFT_PADDLE_DOWN:
   MOV AX,PADDLE_VELOCITY
   ADD PADDLE_LEFT_Y,AX
   MOV AX ,WINDOW_HEIGHT
   SUB AX,PADDLE_HEIGHT
   CMP PADDLE_LEFT_Y,AX
   JG FIX_PADDLE_LEFT_BOTTOM
   JMP CHECK_RIGHT_PADDLE

   FIX_PADDLE_LEFT_BOTTOM:
     MOV PADDLE_LEFT_Y,AX
     JMP CHECK_RIGHT_PADDLE



CHECK_RIGHT_PADDLE:

 CMP AI_LEFT_PADDLE_CONTROLLED,01H
 JE AI_USED
 
KEYS_CHECKING:
 ; O,O FOR LEFT PADDLE UP
 CMP AL,50H ;P
 JE RIGHT_PADDLE_UP
 CMP AL,70H ;p
 JE RIGHT_PADDLE_UP

 ;L,l FOR left PADDLE down
 CMP AL,4CH ;L
 JE RIGHT_PADDLE_DOWN
 CMP AL,6CH ;l
 JE RIGHT_PADDLE_DOWN

 JMP EXIT_PADDLE

 ; FOR SINGLE PLAYER MODE
 AI_USED:
   MOV AX,BALL_Y
   ADD AX,BALL_SIZE
   CMP AX,PADDLE_RIGHT_Y
   JL RIGHT_PADDLE_UP
   MOV AX,PADDLE_RIGHT_Y
   ADD AX,PADDLE_HEIGHT
   CMP AX,BALL_Y
   JL RIGHT_PADDLE_DOWN
   JMP EXIT_PADDLE



 RIGHT_PADDLE_UP:
   MOV AX,PADDLE_VELOCITY
   SUB PADDLE_RIGHT_Y,AX
   
   MOV AX,WINDOW_BOUNDARIES
   CMP PADDLE_RIGHT_Y,AX
   JL FIX_PADDLE_RIGHT_TOP


   JMP EXIT_PADDLE

   FIX_PADDLE_RIGHT_TOP:
     MOV AX,WINDOW_BOUNDARIES
     MOV PADDLE_RIGHT_Y,AX
     JMP EXIT_PADDLE


 RIGHT_PADDLE_DOWN:
   MOV AX,PADDLE_VELOCITY
   ADD PADDLE_RIGHT_Y,AX
   MOV AX ,WINDOW_HEIGHT
   SUB AX,PADDLE_HEIGHT
   CMP PADDLE_RIGHT_Y,AX
   JG FIX_PADDLE_RIGHT_BOTTOM
   JMP EXIT_PADDLE

   FIX_PADDLE_RIGHT_BOTTOM:
     MOV PADDLE_RIGHT_Y,AX
     JMP EXIT_PADDLE





EXIT_PADDLE:
 RET
MOV_PADDLES ENDP
;-----------------------------------
USER_INTERFACE PROC NEAR
 ; DOS INT 21

 ;DRAW PONTS OF LEFT PLAYER
 MOV AH,02H  ;CURSOR POSITION
 MOV BH,00h  ;PAGE NUMBER
 MOV DH,04H  ;ROW
 MOV DL,06H  ;COLUMN
 INT 10h

 MOV AH,09H   ;WRITE  STRING
 LEA DX,TEXT_LEFT_PLAYER_POINTS ; DX POINTER TO STRING
 INT 21H ;PRINTS


 ;DRAW POINTS OF RIGHT PLAYER
 MOV AH,02H  ;CURSOR POSITION
 MOV BH,00h  ;PAGE NUMBER
 MOV DH,04H  ;ROW
 MOV DL,49H  ;COLUMN
 INT 10h

 MOV AH,09H   ;WRITE  STRING
 LEA DX,TEXT_RIGHT_PLAYER_POINTS ; DX POINTER TO STRING
 INT 21H ;PRINTS
  





 RET
USER_INTERFACE ENDP
;---------------------------------------
UPDATE_TEXT_POINTS_LEFT_PLAYER PROC NEAR
 XOR AX,AX
 MOV AL,PADDLE_LEFT_PLAYER_PONTS

 ;CONVERT DECIMAL TO ASCII
 ;ADD 30H DECIMAL TO ASCII
 ADD AL,30H
 MOV [TEXT_LEFT_PLAYER_POINTS],AL




 RET
UPDATE_TEXT_POINTS_LEFT_PLAYER ENDP
;---------------------------------------
UPDATE_TEXT_POINTS_RIGHT_PLAYER PROC NEAR

 XOR AX,AX
 MOV AL,PADDLE_RIGHT_PLAYER_PONTS

 ;CONVERT DECIMAL TO ASCII
 ;ADD 30H DECIMAL TO ASCII
 ADD AL,30H
 MOV [TEXT_RIGHT_PLAYER_POINTS],AL

 RET
UPDATE_TEXT_POINTS_RIGHT_PLAYER ENDP
;---------------------------------------
DRAW_GAME_OVER_UI PROC NEAR


  
  MOV AH,0Bh ;background colour
  MOV BH,00h
  MOV BL,00h 
  INT 10h

  ;WRITE
  MOV AH,02H  ;CURSOR POSITION
  MOV BH,00h  ;PAGE NUMBER
  MOV DH,0CH  ;ROW
  MOV DL,37H  ;COLUMN
  INT 10h

  MOV AH,09H   ;WRITE  STRING
  LEA DX,TEXT_GAME_OVER ; DX POINTER TO STRING
  INT 21H ;PRINTS

  ;-------SHOW WINNER-------

  ;WRITE
  MOV AH,02H  ;CURSOR POSITION
  MOV BH,00h  ;PAGE NUMBER
  MOV DH,0EH  ;ROW
  MOV DL,34H  ;COLUMN
  INT 10h

  CALL UPDATE_WINNER_TEXT

  MOV AH,09H   ;WRITE  STRING
  LEA DX,TEXT_GAME_OVER_WINNER ; DX POINTER TO STRING
  INT 21H ;PRINTS

  ;----DISPLAY MAIN MENU TEXT IN GAME OVER----
  
  ;WRITE
  MOV AH,02H  ;CURSOR POSITION
  MOV BH,00h  ;PAGE NUMBER
  MOV DH,1EH  ;ROW
  MOV DL,50H  ;COLUMN
  INT 10h

  MOV AH,09H   ;WRITE  STRING
  LEA DX,TEXT_GAME_OVER_MAIN_MENU ; DX POINTER TO STRING
  INT 21H ;PRINTS

  ; ----DISPLAY PLAY AGAIN TEXT----
  ;WRITE
  MOV AH,02H  ;CURSOR POSITION
  MOV BH,00h  ;PAGE NUMBER
  MOV DH,2FH  ;ROW
  MOV DL,50H  ;COLUMN
  INT 10h

  MOV AH,09H   ;WRITE  STRING
  LEA DX,TEXT_GAME_OVER_PLAY_AGAIN ; DX POINTER TO STRING
  INT 21H ;PRINTS


 ; Wait for a key press
   MOV AH,00H     
  INT 16H 

; ESC KEY TO PLAY AGAIN 
  CMP AL,1BH
  JE RESTART_GAME

; E,e EXIT TO MAIN MENU  
  CMP AL,'E'
  JE EXIT_TO_MAIN_MENU
  CMP AL,'e'
  JE EXIT_TO_MAIN_MENU
  RET


EXIT_TO_MAIN_MENU:
  MOV GAME_ACTIVE,00h
  MOV CURRENT_SCENE,00h
  RET 

 RESTART_GAME:
  CALL CLEAR_SCREEN
  MOV GAME_ACTIVE,01H
  RET
DRAW_GAME_OVER_UI ENDP 
;-------------------------------------
CLEAR_SCREEN PROC NEAR

  MOV AH,00h ; graphics mode
  MOV AL,13h
  INT 10h

RET
CLEAR_SCREEN ENDP
;-------------------------------------
UPDATE_WINNER_TEXT PROC NEAR
 MOV AL,WINNER_INDEX
 ADD AL,30H
 MOV [TEXT_GAME_OVER_WINNER+7],AL


RET 
UPDATE_WINNER_TEXT ENDP
;------------------------------------
DRAW_MAIN_MENU PROC NEAR

  CALL CLEAR_SCREEN
; ----DISPLAY MAIN MENU TEXT----
  ;WRITE
  MOV AH,02H  ;CURSOR POSITION
  MOV BH,00h  ;PAGE NUMBER
  MOV DH,08H  ;ROW
  MOV DL,0FH  ;COLUMN
  INT 10h
  MOV AH,09H   ;WRITE  STRING
  LEA DX,TEXT_MAIN_MENU ; DX POINTER TO STRING
  INT 21H ;PRINTS

;----DISPLAY SINGLE PLAYER TEXT----
  ;WRITE
  MOV AH,02H  ;CURSOR POSITION
  MOV BH,00h  ;PAGE NUMBER
  MOV DH,0AH  ;ROW
  MOV DL,5EH  ;COLUMN
  INT 10h
  MOV AH,09H   ;WRITE  STRING
  LEA DX,TEXT_MAIN_MENU_SINGLE_PLAYER ; DX POINTER TO STRING
  INT 21H ;PRINTS

;----DISPLAY MULTI PLAYER TEXT----
  ;WRITE
  MOV AH,02H  ;CURSOR POSITION
  MOV BH,00h  ;PAGE NUMBER
  MOV DH,0CH  ;ROW
  MOV DL,0EH  ;COLUMN
  INT 10h
  MOV AH,09H   ;WRITE  STRING
  LEA DX,TEXT_MAIN_MENU_MULTI_PLAYER ; DX POINTER TO STRING
  INT 21H ;PRINTS

MAIN_MENU_CHECK:
; Wait for a key press
  MOV AH,00H      
  INT 16H 

; SINGLE PLAYER MODE
  CMP AL,'S'
  JE SINGLE_PLAYER_MODE
  CMP AL,'s'
  JE SINGLE_PLAYER_MODE


; MULTI PLAYER MODE
  CMP AL,'M'
  JE MULTI_PLAYER_MODE
  CMP AL,'m'
  JE MULTI_PLAYER_MODE

  JMP MAIN_MENU_CHECK


  MULTI_PLAYER_MODE:
   CALL CLEAR_SCREEN
   CALL RESET_POS
   MOV CURRENT_SCENE,01H
   MOV GAME_ACTIVE,01
   MOV AI_LEFT_PADDLE_CONTROLLED,00H
   RET

  SINGLE_PLAYER_MODE:
   CALL CLEAR_SCREEN
   CALL RESET_POS
   MOV CURRENT_SCENE,01H
   MOV GAME_ACTIVE,01H
   MOV AI_LEFT_PADDLE_CONTROLLED,01H
   
  



 


 RET
DRAW_MAIN_MENU ENDP








CODE ENDS
END MAIN
